### ISSUE TITLE
Django 1.9: ImportError: No module named importlib

### ISSUE THREAD

**Issue by barsch** [stephenmcd/django-forms-builder#180]
```
Traceback (most recent call last):
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "d:\python\64\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\forms_builder\forms\models.py", line 12, in <module>
    from forms_builder.forms import fields
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\forms_builder\forms\fields.py", line 9, in <module>
    from forms_builder.forms.utils import html5_field, import_attr
  File "D:\Python\virtualenv\egu\django19\lib\site-packages\forms_builder\forms\utils.py", line 4, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

replacing
    ```from django.utils.importlib import import_module```
with
    ```from importlib import import_module```
solved that issue - see also http://stackoverflow.com/questions/32761566/django-1-9-importerror-for-import-module

**Comment by stephenmcd** [comment]
PR?

**Comment by stephenmcd** [comment]
NVM, fixed 6 months ago:

c1569ac56b81ffbe5a517fa5df81a3f94cc19d27

**Comment by barsch** [comment]
args wrong version :/ - sorry for bothering
