### ISSUE TITLE
Not Django 1.10 compatible

### ISSUE THREAD

**Issue by barsch** [stephenmcd/django-forms-builder#199]
RequestContext user in views.form_sent has been removed in Django 1.10 - see also https://stackoverflow.com/questions/38996878/django-1-10-requestcontext-processors-not-working.

Monkey patching https://github.com/stephenmcd/django-forms-builder/blob/master/forms_builder/forms/views.py#L113-L119 to:

```
def form_sent(request, slug, template="forms/form_sent.html"):
    """
    Show the response message.
    """
    published = Form.objects.published(for_user=request.user)
    context = {"form": get_object_or_404(published, slug=slug)}
    return render(request, template, context)
```
seems to work.

**Comment by jtank38** [comment]
after I add the name to settings.py I keep getting this error
`Unhandled exception in thread started by <function wrapper at 0x7f5e2bb79a28>
Traceback (most recent call last):
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jubanjan/.local/lib/python2.7/site-packages/django/contrib/contenttypes/apps.py", line 7, in <module>
    from .management import (
ImportError: cannot import name update_contenttypes
`
Now it won't run even after I've removed the name from INSTALLED APPS. Any help?
I'm using django 1.10.7

**Comment by stephenmcd** [comment]
97ee3855204d9d6a33c097319e2135a817d5047f
